### ISSUE TITLE
Integrate Umami analytics for bettercollected

### ISSUE THREAD

**Issue by spannercode** [bettercollected/bettercollected#432]
```
As a form creator, 
When I click on 'Analytics' tab on the form details page
I see a complete analytics page as shown on Umami filtered with correct Form URL.
```

Additional notes:
- Here we're interested in analytics for a particular page instead of the website itself, so filtering on URL is important for the backend API but the UI should not show the filter on URL.
- There should be time range selection as in umami dashboard
- No pages section required since we're only interested in single form page.
- The backend should be integrated with bettercollected authentication and should not require separate umami authentication.

<img width="449" alt="Screenshot 2024-08-26 at 08 52 57" src="https://github.com/user-attachments/assets/7a40ca54-8129-442e-aba2-d115975c0fcd">

**Comment by spannercode** [comment]
For umami integration, 
- lets set the user credentials as environment variables; no hardcoded/static credentials to be used on code
- Proxy requests to Umami APIs
- Handle for cases like: upstream umami API not being available, authentication failure (login token expired/invalid, wrong credentials)
- Explore if Umami frontend code can be re-used (Website component ...)

**Comment by spannercode** [comment]
Lets do it on two parts:
1. API (PR for the API changes as mentioned above)
2. Frontend re-using the Umami source (?) (this could be multiple PRs)

**Comment by Prakash-coder** [comment]
**API part accomplished**

1. User credentials set as environment variables.
2. umami upstream not being available is handled by raising our own custom exception response.
3. As the token that we get from umami is encrypted, it is probably not possible to decode. So, for each request, new token has to be generated and I have done it accordingly.

**Comment by Prakash-coder** [comment]
**UI Progress**

1. Major metrics data (pageviews, visitors, visits, bounces, total time) has been successfully rendered.
2. Detailed metrics (OS, countries, referrers, devices) have been fetched through the API; rendering logic is in progress.

**Remaining Tasks**

1. Render the bar chart.
2. Implement filtering of data according to various time units.
3. Render a map based on country data.

**Comment by Prakash-coder** [comment]
### Completed Implementation of the 'Analytics' 

- Integrated Umami analytics for the specific form URL with proper filtering on the backend (without exposing the filter in the UI).
- Integrated with BetterCollected authentication, ensuring no separate Umami authentication is needed.
- Added time range selection similar to the Umami dashboard.
- Added all the relevant metrics, bar chart and detailed data table similar to Umami.

Confirmed functionality. Ready to close this issue. #432
