### ISSUE TITLE
Address dependabot dependency PRs

### ISSUE THREAD

**Issue by spannercode** [bettercollected/bettercollected#435]
Lets update the dependencies on the project to address the reports from Dependabot.

**Comment by Tulsee** [comment]
### Issue Resolved: Dependencies Updated and Dependabot Alerts Reduced

I have updated all the possible package versions in the project based on the reports from Dependabot. The following dependencies were upgraded:

- cryptography - Updated from `42.0.4` to `43.0.1`
- gunicorn - Updated from `20.1.0` to `22.0.0`
- requests - Updated from `2.28.2` to `2.32.2.3`
- And many more packages

As a result of these updates, the number of Dependabot alerts has been significantly reduced from over 100 to just 19. All updates have been tested, and the project builds successfully.

Closing this issue now. 👍

Fixes  #435
